[INFRA] add aws infra: db, s3, config
softwaredelta/GNP pull request #10
Opened 2023-04-11 21:45 UTC by eduardvercaemer

includes:
- pipeline
- buildspec
- cloudformation template no cdloudfront cdn
- proxy settings
- instance connection to s3 bucket
- rds configuration and abstraction
- tls setup
- load balancer redirect
- certificate and dns setup
- health check path
- automatic dns setup

2023-04-11 21:52 UTC, eduardvercaemer commented
Sonar:
https://sonarcloud.io/project/security_hotspots?id=softwaredelta_GNP&pullRequest=10&hotspots=AYdySFt3yNRNH_Ekvef-

La utilización de ENV aquí es segura, es una configuración local y de desarrollo únicamente.

2023-04-11 22:30 UTC, iangg29 requested changes
LGTM

2023-04-11 22:30 UTC, iangg29 commented on .vscode/settings.json
> +}
IDEs config folders should not be pushed to repo.

(Example PR #9 )

2023-04-12 00:06 UTC, alfredohuerta approved these changes

2023-04-12 00:15 UTC, alfredohuerta approved these changes

2023-04-12 00:39 UTC, merged